# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firestoredummy' do
 pod 'Firebase/Core'
 pod 'Firebase/Firestore'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
